### ISSUE TITLE
Scaffolds labels cropped 

### ISSUE THREAD

**Issue by ManonBoosten** [SamiLhll/macrosyntR#3]
The labels of the scaffolds with few genes get cropped, is there a way to display them entirely?

**Comment by SamiLhll** [comment]
Hey Manon, Thanks for reporting this !
What's returned by the function plot_oxford_grid() is a ggplot2 object allowing you to customize how it's displayed using 
the theme() function if you have ggplot2 loaded in your environment.

The labels of the chromosomes can be displayed entirely by setting the option strip.clip = "off" in theme()
 as the plot is built in such a way that the pairwise chromosome comparisons are displayed in facets . 
Here is how to call it : 

plot_oxford_grid(...) + theme(strip.clip = "off")

In addition you can change the orientation of the text. For instance, you can set the orientation to 45 degrees of the 
labels of the first species as following (it's 90 degrees by default in macrosyntR) : 

plot_oxford_grid(...) + theme(strip.clip = "off",
                                                  strip.text.x = element_text(angle = 45)

In the cases where you have many chromosomes with very long names the labels will overlap. I recommend changing the names to the minimum to make things more readable. If there's a long pattern that is conserved in all the chromosome names you can achieve this using stringr as following : 

levels(my_orthologs$sp1.Chr) <- stringr::str_replace(levels(my_orthologs$sp1.Chr),
                                                                                          "very_long_scaffold_pattern",
                                                                                          "short_scaffold_name")

I'll add this in the vignette of the next update.
Cheers,
Sami
